default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: new_library_development
  username: new_library
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: new_library_test

production:
  <<: *default
  database: new_library_production
  username: new_library
  password: <%= ENV['NEW_LIBRARY_DATABASE_PASSWORD'] %>